services:
  db:
    healthcheck:
      interval: 10s
      retries: 3
      test:
        [
          "CMD",
          "healthcheck.sh",
          "--su-mysql",
          "--connect",
          "--innodb_initialized"
        ]
      timeout: 5s
    image: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=changeme
      - MARIADB_PASSWORD=changeme
      - MARIADB_USER=user
      - MARIADB_DATABASE=movies
    volumes:
      - db-mariadb:/var/lib/mysql
    expose:
      - 3306

  api:
    build:
      context: .
      dockerfile: Howest.Movies.WebApi/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./Howest.Movies.WebApi/posters:/app/posters
      - ./Howest.Movies.WebApi/appsettings.Development.json:/app/appsettings.json
    ports:
      - 5000:8080
    
  web:
    build:
      context: .
      dockerfile: Howest.Movies.WebApp/Dockerfile
    depends_on:
      - api
    volumes:
      - ./Howest.Movies.WebApp/wwwroot/appsettings.Development.json:/usr/share/nginx/html/appsettings.json
    ports:
        - 5050:8080

volumes:
  db-mariadb: