services:
  db:
    image: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=changeme
      - MARIADB_PASSWORD=changeme
      - MARIADB_USER=user
      - MARIADB_DATABASE=movies
    volumes:
      - db-mariadb:/var/lib/mysql
    ports:
      - 3306:3306

  api:
    build:
      context: .
      dockerfile: Howest.Movies.WebApi/Dockerfile
    depends_on:
        - db
    volumes:
      - posters:/app/posters
    

  web:
    build:
      context: .
      dockerfile: Howest.Movies.WebApp/Dockerfile
    depends_on:
      - api

volumes:
  db-mariadb:
  posters: